spring:
  datasource:
    url: jdbc:h2:file:./camunda-h2-database
  jpa:
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true
      path: /h2-console

  mail:
    host: smtp.ethereal.email
    port: 587
    username: josue.macgyver26@ethereal.email
    password: 3PXn7CrK2Y8HbPFe6a
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

camunda:
  bpm:
    admin-user:
      id: demo
      password: demo
  webapp:
    security:
      enabled: true

app:
  admin:
    email: admin@example.com
  mail:
    from: no-reply@innovation.local
